id: alien-cloudify-2-paas-provider
name: Cloudify 2 PaaS provider
version: ${project.version}
description: >
  Plugin that contains the PaaS Provider for cloudify v2.
configuration_class: alien4cloud.paas.cloudify2.PluginContextConfiguration
component_descriptors:
  - bean_name: cloudify-paas-provider
    name: Cloudify 2 PaaS Provider
    description: >
      A PaaS provider that deploys applications on cloudify 2.x
      Make sure that you configure the url of the cloudify Rest API.
